# Generated by Django 4.2.11 on 2026-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voicesample',
            new_name='voice_sampl_user_id_55791c_idx',
            old_name='vsample_user_idx',
        ),
        migrations.RenameIndex(
            model_name='voicetrainingjob',
            new_name='voice_train_user_id_22402e_idx',
            old_name='vjob_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='voicetrainingjob',
            new_name='voice_train_celery__6baedf_idx',
            old_name='vjob_celery_idx',
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='noise_floor_db',
            field=models.FloatField(blank=True, help_text='Ambient noise floor measured during upload validation', null=True),
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='sample_index',
            field=models.PositiveSmallIntegerField(help_text='Which of the 5 samples this is (1–5)'),
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='sample_rate',
            field=models.PositiveIntegerField(default=16000, help_text='Expected 16000 Hz (16 kHz mono WAV)'),
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='storage_path',
            field=models.TextField(help_text='Supabase Storage path: voice-samples/{user_id}/sample_{n}.wav'),
        ),
        migrations.AlterField(
            model_name='voicesample',
            name='storage_url',
            field=models.TextField(blank=True, default='', help_text='Signed URL (refreshed on demand — not stored permanently)'),
        ),
        migrations.AlterField(
            model_name='voicesentence',
            name='position',
            field=models.PositiveSmallIntegerField(help_text='Display order 1–5 on the training screen'),
        ),
        migrations.AlterField(
            model_name='voicetrainingjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery AsyncResult task ID for status polling', max_length=64),
        ),
        migrations.AlterField(
            model_name='voicetrainingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending — waiting for Celery worker'), ('processing', 'Processing — downloading samples and computing embedding'), ('completed', 'Completed — embedding saved to user profile'), ('failed', 'Failed — see error_message')], db_index=True, default='pending', max_length=12),
        ),
    ]
