# Generated by Django 4.2.11 on 2026-04-04 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='conversatio_updated_c163ba_idx',
            old_name='conv_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messages_convers_38b855_idx',
            old_name='msg_conv_time_idx',
        ),
        migrations.AlterUniqueTogether(
            name='messagedeletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='messagedeletion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messagedeletion',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.message'),
        ),
        migrations.AddIndex(
            model_name='messagetranslation',
            index=models.Index(fields=['message', 'language'], name='message_tra_message_2a22c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedeletion',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_deletion'),
        ),
        migrations.AlterModelTable(
            name='messagedeletion',
            table=None,
        ),
    ]
