# Generated by Django 4.2.11 on 2026-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='email_otps_email_18aced_idx',
            old_name='emailotp_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_email_4b85f2_idx',
            old_name='users_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_display_32b2ed_idx',
            old_name='users_display_name_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_supabas_9d38fd_idx',
            old_name='users_supabase_uid_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_is_onli_345e4c_idx',
            old_name='users_presence_idx',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email verified (OTP or Supabase callback)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('pl', 'Polish'), ('tr', 'Turkish'), ('ru', 'Russian'), ('nl', 'Dutch'), ('cs', 'Czech'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('hu', 'Hungarian'), ('hi', 'Hindi')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_uid',
            field=models.CharField(blank=True, help_text='Supabase Auth UID — used to verify JWT sub claim', max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='voice_embedding',
            field=models.JSONField(blank=True, help_text='XTTS speaker embedding vector (256-dim list)', null=True),
        ),
    ]
