# Generated by Django 4.2.11 on 2026-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='friend_requ_to_user_f1ac62_idx',
            old_name='freq_to_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='friendrequest',
            new_name='friend_requ_from_us_41dc33_idx',
            old_name='freq_from_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_user_a__13f666_idx',
            old_name='friendship_user_a_idx',
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_user_b__48c4f2_idx',
            old_name='friendship_user_b_idx',
        ),
        migrations.RenameIndex(
            model_name='userdevice',
            new_name='user_device_user_id_4ec133_idx',
            old_name='userdevice_user_idx',
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='message',
            field=models.CharField(blank=True, default='', help_text='Optional short message from requester', max_length=200),
        ),
    ]
