# Generated by Django 4.2.11 on 2026-04-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callroom',
            new_name='call_rooms_caller__c3243f_idx',
            old_name='call_caller_idx',
        ),
        migrations.RenameIndex(
            model_name='callroom',
            new_name='call_rooms_callee__a9e6d5_idx',
            old_name='call_callee_idx',
        ),
        migrations.RenameIndex(
            model_name='callroom',
            new_name='call_rooms_status_1f4678_idx',
            old_name='call_status_idx',
        ),
        migrations.RenameIndex(
            model_name='callroom',
            new_name='call_rooms_room_id_9685db_idx',
            old_name='call_room_id_idx',
        ),
    ]
